### ISSUE TITLE
In test environment, portalContainer.append and document.body.append both throw TypeError

### ISSUE THREAD

**Issue by sheminusminus** [segmentio/evergreen#602]
## Issue: Bug Report

In a test environment, components accessing `portalContainer.append` and `document.body.append` throw TypeErrors (`x.append is not a function`).

## Versions

Evergreen: 4.18.1
React: 16.6.0

## Screenshots

<img width="785" alt="Screen Shot 2019-07-24 at 3 04 01 PM" src="https://user-images.githubusercontent.com/9907610/61824695-49b27a80-ae24-11e9-8ad0-6da8a971a890.png">

## Expected

These functions should not be called if they do not exist (if we are not in a full DOM env).

## Actual

DOM functions are called when they do not exist.

## Browser

Jest's js-dom 24.0.0

## OS

macOS 10.14.5

## Example Error Output

```
TypeError: portalContainer.append is not a function
      
      at new Portal (node_modules/evergreen-ui/commonjs/portal/src/Portal.js:50:21)
      at constructClassInstance (node_modules/react-dom/cjs/react-dom.development.js:11864:18)
      at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:13681:5)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:14489:16)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:17014:12)
      at workLoop (node_modules/react-dom/cjs/react-dom.development.js:17054:24)
      at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:17133:7)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:17993:7)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:17901:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:17873:3)
      at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:18108:7)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:1212:14
      at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:393:15)
      at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:929:29)
      at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1653:25)
      at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:928:21)
      at Object.it (src/_components/toolbar/components/ToolbarButton/ToolbarButton.test.js:30:49)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
```

**Comment by totaldis** [comment]
https://github.com/segmentio/evergreen/pull/517/files#diff-e1995d8ad5cb25e5daf2bf3285726d93

**Comment by mshwery** [comment]
This should be resolved via https://github.com/segmentio/evergreen/pull/692
